apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

namespace: frontend

patchesStrategicMerge:
- deployment-patch.yaml
- configmap-patch.yaml

resources:
- ingress.yaml
- hpa.yaml
- pdb.yaml
