apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  url: https://argocd.example.com
  
  # Configurações específicas para produção
  statusbadge.enabled: "false"
  resource.exclusions: |
    - apiGroups: [""]
      kinds: ["Secret"]
      clusters: ["prod-cluster"]
      names: ["prod-sensitive-*"]
  
  # Configurações de segurança reforçadas para produção
  application.instanceLabelKey: argocd.argoproj.io/instance
