apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

namespace: api-service-dev

patchesStrategicMerge:
- deployment-patch.yaml
- configmap-patch.yaml

resources:
- ingress.yaml
