apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  policy.csv: |
    # Políticas específicas para o ambiente dev
    p, role:dev, applications, *, dev-cluster/*, allow
    p, role:dev, logs, get, dev-cluster/*, allow
    
    # Dev leads podem gerenciar projetos no ambiente dev
    p, role:dev-lead, applications, *, dev-cluster/*, allow
    p, role:dev-lead, projects, *, dev-cluster/*, allow
    
    # Mapeamento de grupos
    g, dev-leads, role:dev-lead
