apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  url: https://argocd-dev.example.com
  
  # Ajustes específicos para ambiente dev
  resource.exclusions: |
    - apiGroups: [""]
      kinds: ["ConfigMap"]
      clusters: ["dev-cluster"]
      names: ["dev-only-config"]
