# Esta é uma versão simplificada para o teste
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: argocd
  namespace: argocd
spec:
  server:
    route:
      enabled: true
    ingress:
      enabled: false
  dex:
    enabled: true
    openShiftOAuth: false
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 250m
        memory: 128Mi
  ha:
    enabled: true
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 250m
        memory: 128Mi
  rbac:
    defaultPolicy: 'role:readonly'
    policy: |
      g, system:cluster-admins, role:admin
      g, sre-team, role:admin
    scopes: '[groups]'
  repositories:
    - name: app-repo
      url: https://github.com/organization/application-repo.git
    - name: platform-repo
      url: https://github.com/organization/platform-repo.git
  sso:
    provider: dex
    dex:
      config: |
        connectors:
          - type: github
            id: github
            name: GitHub
            config:
              clientID: $GITHUB_CLIENT_ID
              clientSecret: $GITHUB_CLIENT_SECRET
              orgs:
              - name: your-github-org
  version: v2.7.4
