apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
type: Opaque
stringData:
  # Esses valores seriam definidos usando um Secret Management em um ambiente real
  admin.password: "$2a$10$someHashedPasswordForTesting"
  admin.passwordMtime: "2023-01-01T00:00:00Z"
  server.secretkey: "SomeRandomGeneratedKey"
  dex.github.clientSecret: "GitHubClientSecretWouldGoHere"
