apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
data:
  policy.default: role:readonly
  policy.csv: |
    # Políticas RBAC do ArgoCD
    p, role:org-admin, applications, *, */*, allow
    p, role:org-admin, clusters, *, *, allow
    p, role:org-admin, repositories, *, *, allow
    p, role:org-admin, projects, *, *, allow

    # Devs só podem ver e sincronizar aplicações nos ambientes dev
    p, role:dev, applications, get, dev-cluster/*, allow
    p, role:dev, applications, sync, dev-cluster/*, allow

    # SREs podem gerenciar todos os ambientes
    p, role:sre, applications, *, */*, allow
    p, role:sre, clusters, get, *, allow
    
    # Mapeamento de grupos
    g, sre-team, role:sre
    g, dev-team, role:dev
    g, system:cluster-admins, role:org-admin
