name: PR CI
on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: read
  security-events: write

jobs:
  ci:
    uses: central-crdc/governance/.github/workflows/pr-ci.yml@main
