apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-service
  namespace: argocd
spec:
  source:
    path: workloads/apps/api-service/overlays/dev
  destination:
    server: https://kubernetes.dev.example.com
    namespace: api-service-dev
